# Generated by Django 3.2 on 2021-04-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210418_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
